### ISSUE TITLE
Meshy API to integrate in our existing website

### ISSUE THREAD

**Issue by RASHMI232** [0x00019913/meshy#1]
Is there any API to integrate to measure the thickness and check the printability of the model

**Comment by 0x00019913** [comment]
Hey!

There's no API because meshy is a humble static-page app. You'll have to take the modules and do it manually. (BTW, I was a total noob when I designed this functionality, so it's actually going to be changing when I push the module I'm currently working on, but there is enough now that you can do it yourself.)

**The idea is to build an octree based on the mesh, then use that to cast rays into the mesh and see where they hit. If the hit is too close, then the mesh is too thin.**

You need to do this:

1. Get octree.js and utils.js.
2. Build an octree of your mesh - the constructor looks like:
`var octree = new Octree(depth, origin, size, faces, vertices)`
3. For every face of the mesh, calculate the negative normal (`var negativeNormal = face.normal.clone().negate()`) and the center of the face. Then call `var hit = octree.castRay(faceCenter, negativeNormal)`. This returns the closest point inside the mesh where the ray hits the interior of a face. (NB: it may return null if it doesn't hit.) Then you just calculate the distance of that point to faceCenter and see if it's below your thickness threshold.

The octree constructor arguments are as follows:
- `depth`: depth of the octree, such that there aren't too many faces per leaf node; I use the heuristic `Math.round(Math.log(faces.length)*0.6)`, but you can decide this for yourself.
- `origin`, `size`: a `THREE.Vector3` and a number that specify the lowest vertex and side length of a cube that completely encloses the model and is strictly larger than the model. For example, if your mesh's lower bounds are `[-1, -2, -3]` on `x, y, z` and the mesh's sizes are `[2, 4, 6]` on `x, y, z`, then `origin` could be `[-1.1, -2.1, -3.1]` and `size` could be `6.2`.
- `faces`, `vertices`: arrays of faces and vertices from your mesh - get them like `mesh.geometry.faces`, etc.

Possible improvements:
1. The quality of the thickness visualization is limited because it only casts from the center of a face. You can instead sample your faces to account for large or long-but-narrow faces.
2. You can cast multiple rays in a cone instead of just one along the negative normal - see "Fast Approximation of the Shape Diameter Function" by Kovacic et al. That should give a better approximation for the true local thickness, but it'll be more expensive.

Lemme know if you have any questions. :D
